envVarGroups:
  - name: mongo-secrets
    envVars:
      - key: MONGO_URI
        fromSecret: MONGO_URI

services:
  - type: web
    name: url-shortener
    repo: https://github.com/hershy8094/boilerplate-project-urlshortener
    branch: main
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    region: oregon
    plan: starter
    autoDeploy: true
    envVarGroups:
      - mongo-secrets
    healthCheckPath: /
